# Собственный класс-исключение для заданий 2, 3
class CustomException(Exception):
    """Кастомное исколючение"""
    pass
